version: 2
jobs:
  build:
    docker:
      - image: choria/packager:el7-go1.13-puppet

    working_directory: /go/src/github.com/choria-io/mcorpc-agent-provider

    environment:
      GO111MODULE: "on"
      CGO_ENABLED: "0"
      PATH: /go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:/opt/puppetlabs/bin

    steps:
      - checkout
      - run: go mod download
      - run: go get github.com/onsi/ginkgo/ginkgo
      - run: go get -u honnef.co/go/tools/cmd/staticcheck
      - run: go get -u github.com/client9/misspell/cmd/misspell
      - run: go list ./...|xargs staticcheck
      - run: find . -type f -name "*.go" | grep -v "/vendor/" | xargs misspell -error -locale US -i flavour
      - run: ginkgo -r -skipMeasurements mcorpc
